spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gfg
    username: root
    password: 123456
  application:
    name: employee-service
server:
  port: 8080
  servlet:
    context-path: /employee-service