spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gfg
    username: root
    password: 123456
  application:
    name: address-service
server:
  port: 8081
  servlet:
    context-path: /address-service